config/routes.rb
Rails.application.routes.draw do
  get '/user_records/dropdown', to: "user_records#dropdown"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :user_records
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_record.rb
class UserRecord < ApplicationRecord
    belongs_to :user
    validates :client_name, :presence => true
    validates :project_name, :presence => true
    validates :activity_type, :presence => true
    validates :date, :presence => true, :format => {
        :with => /\A\d{4}-(((0)[0-9])|((1)[0-2]))-([0-2][0-9]|(3)[0-1])\z/,
        :message => "Date format invalid"
    }
    validates :start_time, :presence => true, :format => {
        :with => /\A((1[0-2]|0?[1-9]):([0-5][0-9])(\s)?([AaPp][Mm]))\z/,
        :message => "Time format invalid"
    }
    validates :end_time, :presence => true, :format => {
        :with => /\A((1[0-2]|0?[1-9]):([0-5][0-9])(\s)?([AaPp][Mm]))\z/,
        :message => "Time format invalid"
    }
    validates :description, :presence => true
    ACTIVITY_TYPES = ["Client Call","Code Review","Deployment","Development","Meeting","Miscellaneous","Support","Testing"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_records_controller.rb
class UserRecordsController < ApplicationController
    def index
        @user_records = current_user.user_records.order('date DESC')
    end
    
    def show
        @user_record = UserRecord.find(params[:id])
    end
    
    def new
        @user_record ||=  UserRecord.new
    end

    def edit
        @user_record = UserRecord.find(params[:id])
    end
    
    def create
        # render plain: params[:user_record].inspect
        # @user_record = UserRecord.new(user_record_params)
        @user_record = current_user.user_records.create(user_record_params)
        if @user_record.save
            flash[:notice] = "Success!"
            redirect_to @user_record
        else
            # flash[:alert] = @user_record.errors.full_messages.join('<br>')
            render "new"
        end
    end

    def update
        @user_record = UserRecord.find(params[:id])
        if @user_record.update(user_record_params)
            flash[:notice] = "Success!"
            redirect_to @user_record
        else
            render "edit"
        end
    end

    def dropdown
        @client_nm = params[:client_name]
        @client = Client.where(client_name: @client_nm).first
        if @client
            render :json => @client.projects.collect{|c| [c.id, c.project_name]}
        else
            render json: []
        end
    end

    private
        def user_record_params
            params.require(:user_record).permit(:client_name, :project_name, :activity_type, :date, :start_time, :end_time, :description)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_records_helper.rb
module UserRecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeCamp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="https://user-images.githubusercontent.com/1921301/34717722-482d87c2-f534-11e7-8aad-6d1a9d12c395.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-brand">
          TimeCamp
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Home', welcome_index_path, :style => 'text-decoration:none' %></li>
        <% if current_user %>
            <li><%= link_to 'Fill Timesheet', new_user_record_path, :style => 'text-decoration:none' %></li>
            <li><%= link_to 'View my timesheet entries', user_records_path, :style => 'text-decoration:none' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-decoration:none;">
              <span class="glyphicon glyphicon-user"></span>&nbsp &nbsp<%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="width:215px">
              <a class="dropdown-item"><%= link_to 'Change Password', edit_user_registration_path, :style => 'text-decoration:none;padding-left:30px;' %></a><br>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item"><%= link_to 'Log Out', destroy_user_session_path , method: :delete, :style => 'text-decoration:none;padding-left:30px' %></a>
            </div>
          </li>
        </ul>
        <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path, :style => 'text-decoration:none' %></li>
            <li><%= link_to 'Log In', new_user_session_path, :style => 'text-decoration:none' %></li>
            <li><%= link_to 'Log In as Admin', admin_root_path, :style => 'text-decoration:none' %></li>
        </ul>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/user_records/_form.html.erb
<div style="width:800px;">
        <%= form_with scope: :user_record, url: user_records_path, local: true do |form| %>
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <p>
                <%= form.label :client_name %><br>
                <%= form.collection_select(:client_name, Client.all, :client_name,:client_name) %>
              </p>
            </div>
            <div class="col-md-4">
              <p>
                <%= form.label :project_name %><br>
                <%= form.select(:project_name, []) %>
                <span id="empty_project" style="color:red"></span>
              </p>
            </div>
            <div class="col-md-4">
              <p>
                <%= form.label :activity_type %><br>
                <%= form.select(:activity_type, UserRecord::ACTIVITY_TYPES) %>
              </p>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-4">
              <p>
                <%= form.label :date %><br>
                <%= form.text_field :date, placeholder: 'DD-MM-YYYY', class: 'flatpikrcal', readonly: true %>
                <span id="datepick" style="color:red"></span>
              </p>
            </div>
            <div class="col-md-4">
              <p>
                <%= form.label :start_time %><br>
                <%= form.text_field :start_time, placeholder: 'HH:MM AM/PM', class: 'flatpickrstart flatpickr-input active', readonly: true %>
                <span id="startpick" style="color:red"></span>
              </p>
            </div>
            <div class="col-md-4">
              <p>
                <%= form.label :end_time %><br>
                <%= form.text_field :end_time, placeholder: 'HH:MM AM/PM', class: 'flatpickrend flatpickr-input active', readonly: true %>
                <span id="endpick" style="color:red"></span>
              </p>
            </div>
          </div>
          <br>
          <p>
            <%= form.label :description %><br>
            <%= form.text_area :description, :required => 'required' %>
          </p>
          <br>
          <p>
            <%= form.submit :class => 'button' %>
          </p>
        </div>
        <br>
        <% end %>
    </div>

app/views/user_records/edit.html.erb
<script>
    $(document).on('click', '.button', function(){
      var date = document.getElementById("user_record_date").value;
      var start = document.getElementById("user_record_start_time").value;
      var end = document.getElementById("user_record_end_time").value;
      var project = document.getElementById("user_record_project_name").value;
      var status = false;
      if(project.length<1){
          document.getElementById("empty_project").innerHTML = "Please select the Project Name."
          status = false;
      }
      else{
          status = true;
      }
      if(date.length<1){
          document.getElementById("datepick").innerHTML = "Please select the Date.";
          status = false;
      }
      else{
          
          status = true;
      }
      if(start.length<1){
          document.getElementById("startpick").innerHTML = "Please enter the Start Time.";
          status = false;
      }
      else{
        status = true;
      }
      if(end.length<1){
          document.getElementById("endpick").innerHTML = "Please enter the End Time.";
          status = false;
      }
      else{
        status = true;
      }
    return status;
    });
    
    
    $(document).on('click', '#user_record_client_name', function(){
        var client_nm = $(this).val();
        document.getElementById("empty_project").innerHTML = "";
        $.get('/user_records/dropdown', {client_name: client_nm}, function(data){
            $("#user_record_project_name").html("");
            $.each(data, function(index, value){
              $("#user_record_project_name").append( "<option value='" + data[index][1] + "'>" + data[index][1] + "</option>" );
            });
          
        });
    });

    $(document).on('click', '#user_record_project_name', function(){
      if ( $('#user_record_project_name').children().length == 0 ){
        document.getElementById("empty_project").innerHTML = "Please select Client first.";
      }
    });
</script>
<style>
  #user_record_client_name, #user_record_project_name, #user_record_activity_type{
    width: 125px;
    height: 25px;
  }
</style>
<%= render "devise/shared/error_messages", resource:  @user_record %>
<div style="margin-left: 60px;">
    <h2>Update Timesheet Entry</h2>
    <br>
    <%= render "form"%>
</div>

app/views/user_records/index.html.erb
<h2 style='padding-left:60px;'>Timesheet Entries</h2>
<br>
<div style='padding-left:60px; padding-right:60px'>
    <table class="table" style='padding-left:60px;'>
      <thead class="thead-dark">
        <tr>
            <th>Client Name:</th>
            <th>Project Name:</th>
            <th>Activity Type:</th>
            <th>Date:</th>
            <th>Start Time:</th>
            <th>End Time:</th>
            <th>Description:</th>
            <th></th>
        </tr>
      </thead>
      <tbody>
        <% @user_records.each do |user_record| %>
            <tr>
            <td><%= user_record.client_name %></td>
            <td><%= user_record.project_name %></td>
            <td><%= user_record.activity_type %></td>
            <td><%= user_record.date.strftime("%d-%m-%Y") %></td>
            <td><%= user_record.start_time %></td>
            <td><%= user_record.end_time %></td>
            <td><%= user_record.description %></td>
            <td><%= link_to 'Edit', edit_user_record_path(user_record) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/user_records/new.html.erb
<script>
    $(document).on('click', '.button', function(){
      var date = document.getElementById("user_record_date").value;
      var start = document.getElementById("user_record_start_time").value;
      var end = document.getElementById("user_record_end_time").value;
      var project = document.getElementById("user_record_project_name").value;
      var status = false;
      if(project.length<1){
          document.getElementById("empty_project").innerHTML = "Please select the Project Name."
          status = false;
      }
      else{
          status = true;
      }
      if(date.length<1){
          document.getElementById("datepick").innerHTML = "Please select the Date.";
          status = false;
      }
      else{
          status = true;
      }
      if(start.length<1){
          document.getElementById("startpick").innerHTML = "Please enter the Start Time.";
          status = false;
      }
      else{
        status = true;
      }
      if(end.length<1){
          document.getElementById("endpick").innerHTML = "Please enter the End Time.";
          status = false;
      }
      else{
        status = true;
      }
    return status;
    });
    
    
    $(document).on('click', '#user_record_client_name', function(){
        var client_nm = $(this).val();
        document.getElementById("empty_project").innerHTML = "";
        $.get('/user_records/dropdown', {client_name: client_nm}, function(data){
            $("#user_record_project_name").html("");
            $.each(data, function(index, value){
              $("#user_record_project_name").append( "<option value='" + data[index][1] + "'>" + data[index][1] + "</option>" );
            });
          
        });
    });

    $(document).on('click', '#user_record_project_name', function(){
      if ( $('#user_record_project_name').children().length == 0 ){
        document.getElementById("empty_project").innerHTML = "Please select Client Name first.";
      }
    });
</script>
<style>
  #user_record_client_name, #user_record_project_name, #user_record_activity_type, #user_record_date, #user_record_start_time, #user_record_end_time{
    width: 125px;
    height: 25px;
  }
</style>
<%= render "devise/shared/error_messages", resource:  @user_record %>
<div style="margin-left: 60px;">
    <h2>Fill Timesheet</h2>
    <br>
    <%= render "form" %>
</div>

app/views/user_records/show.html.erb
<div style="margin-left: 60px;">
  <h2>Following timesheet entry successfully saved:</h2>
  <br>
  <div style="width:800px;">
      <p>
        <strong>Client Name:</strong>
        <%= @user_record.client_name %>
      </p>
      
      <p>
        <strong>Project Name:</strong>
        <%= @user_record.project_name %>
      </p>

      <p>
        <strong>Activity Type:</strong>
        <%= @user_record.activity_type %>
      </p>

      <p>
        <strong>Date:</strong>
        <%= @user_record.date %>
      </p>

      <p>
        <strong>Start Time:</strong>
        <%= @user_record.start_time %>
      </p>

      <p>
        <strong>End Time:</strong>
        <%= @user_record.end_time %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @user_record.description %>
      </p>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>TimeCamp</h1>
  <p>Created by: Dewanshu Chhatlani</p> 
</div>

  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>User</h3>
      <p>A user can perform the following actions:</p>
      <p>1. Login.</p>
      <p>2. Sign up.</p>
      <p>3. Change password</p>
      <p>4. Fill his/her timesheet.</p>
      <p>5. View his/her timesheet entries.</p>
      
    </div>
    <div class="col-sm-4">
      <h3></h3>
      <p></p>
      <p></p>
    </div>
    <div class="col-sm-4">
      <h3>Admin</h3>        
      <p>An admin can do the following activities:</p>
      <p>1. Log In as Admin.</p>
      <p>2. View all the timesheet entries by all the users.</p>
      <p>3. Edit a particular timesheet entry.</p>
      <p>4. Delete a particular timesheet entry.</p>
    </div>
  </div>
</div>